*** Variables ***
#Nav bar
${MENU.BUTTON}          id=react-burger-menu-btn
${CLOSE.MENU.BUTTON}    id=react-burger-cross-btn
${ALL.ITEM.MENU}        id=inventory_sidebar_link
${ABOUT.MENU}           id=about_sidebar_link
${LOGOUT.MENU}          id=logout_sidebar_link
${RESET.STATE.MENU}     id=reset_sidebar_link
${CART.BUTTON}          //div[contains(@class,"shopping_cart_container")]
${CART.QUANTITY.BADGE}  //span[@class="shopping_cart_badge"]